# @package model.objectives.virtual_normal

_target_: moai.supervision.losses.depth.VirtualNormal
delta_cos: 0.867
delta_diff_x: 0.01
delta_diff_y: 0.01
delta_diff_z: 0.01
delta_z: 0.0001
sample_ratio: 0.15
ignore_perc: 0.25