# @package model.parameters.groups.model5

_target_: moai.parameters.selectors.model.ModelParameterSelector
modules: null # optional
monads: null # optional
parameters: null # optional
force_grad: true