# @package model.objectives.interpenetration

_target_: moai.supervision.losses.mesh.interpenetration.Interpenetration
max_collisions: 128
df_cone_height: 0.0001
penalize_outside:  true
point2plane: false
part_segmentation: null
ignore_part_pairs:
  - "9,16"
  - "9,17"
  - "6,16"
  - "6,17"
  - "1,2"
  - "12,22"