# @package model.architecture

_target_: torchvision.models.resnet34
pretrained: false
progress: true
num_classes: ${NUM_CLASSES}
zero_init_residual: false
groups: 1
width_per_group: 64
replace_stride_with_dilation: null