# @package model.architecture

_target_: torchvision.models.wide_resnet101_2
pretrained: false
progress: true
num_classes: ${NUM_CLASSES}
zero_init_residual: false
groups: 1
replace_stride_with_dilation: null