# @package model.modules.encoder

_target_: moai.modules.lightning.MLP

configuration:
  in_features: ???
  out_features: ???
  blocks: ???
  linear:
    type: ???
    activation:
      type: ???
  prediction:
    type: ???
    activation:
      type: ???