# @package model.modules.hourglass

_target_: moai.modules.lightning.Hourglass
features: 256
depth: 4
convolution: conv2d
activation: relu_bn2d
residual: preactiv_bottleneck
downscale: maxpool2d_aa
upscale: upsample2d