# @package model.components.start_transition

_target_: moai.components.lightning.highres.StartTransition
identity:
  convolution: ${model.configuration.global.convolution}
  activation: ${model.configuration.global.activation}
  kernel_size: 3
  stride: 1
  padding: 1
branched:
  convolution: ${model.configuration.global.convolution}
  activation: ${model.configuration.global.activation}
  downscale: none # maxpool2d
  kernel_size: 3
  stride: 2
  padding: 1