# @package model

_target_: moai.networks.lightning.torchvision.Classifier
configuration:
  io:
    image: color
    out: prediction
architecture:
  _target_: torchvision.models.resnet50
  pretrained: false
  progress: true
  num_classes: ${NUM_CLASSES}
