# @package model.components.latent_dist_predictor

_target_: moai.components.distribution.basic.Basic
mean_module:
  type: linear
  activation:
    type: none
  in_features: ???
  out_features: ???
sigma_module:
  type: linear
  activation:
    type: none
  in_features: ???
  out_features: ???