# @package model.components.latent_dist_predictor

_target_: moai.components.lightning.distribution.Homeomorphic
mean_module:
  input_dims: ???
  output_dims: ???
sigma_module:
  input_dim: ???
  z_dim: ???