# @package _global_

_helpers_:
  optimizer_common: &lbfgsls
    type: lbfgsls
    params:
      max_iter: 30
      lr: 1.0

_moai_:
  _flows_:
    initialize_translation:
      joints2d: [keypoints]
      joints3d: [body.joints]
      out: [init_trans]
    preprocess:
      embedding:
        void: [color]
        out: [embedding]
      translation:
        void: 
          # - color
          - ${mi:"color -1"}
        out: [translation]
      betas:
        void: [color]
        out: [betas]
      vposer2:
        decode: [embedding]
        out: [decoded]
      smplx:
        pose: [decoded.pose]
        shape: [betas]
        out: [body]
    postprocess:
      weak_perspective_camera:
        points: [body.joints]
        translation: [translation]
        image: [color]
        out: [joints2d]
      index:
        tensor: [joints2d, keypoints]
        out: [torso_joints2d, torso_keypoints]
      binary:
        tensor: [init_trans]
        out: [z_mask]
      openpose_split:
        joints: [joints2d, keypoints, confidence]
        out: [split_joints2d, split_keypoints, split_confidence]
  _collections_:
    _optimizers_:
      initial_torso_fit: 
        <<: *lbfgsls
        groups: global  # groups: expressive # global
      fine_fit_stage1:
        <<: *lbfgsls
        groups: [global, expressive] # groups: expressive # [global, expressive]    
    _criteria_:
      bad_fit:
        rmse:
          # gt: [keypoints]
          # pred: [joints2d]
          rmse: [metrics.rmse]
          threshold: [10000.3] # pixels
  _run_:
    fit:
      batch:
        initialize_torso:
          steps: # graphs
            - preprocess
            - initialize_translation
        initial_torso_fit:
          iterations: 5
          optimizer: initial_torso_fit
          # scheduler: null
          steps:
            - preprocess
            - postprocess
          objective: initial_torso_fit              
      # epoch:
      #   termination: 
        # - milestone: 30
        #   batch:
        #     initialize_torso:
        #       steps: # graphs
        #         - preprocess
        #         - initialize_translation
        #     initial_torso_fit:
        #       iterations: 5
        #       optimizer: initial_torso_fit
        #       # scheduler: null
        #       steps:
        #         - preprocess
        #         - postprocess
        #       objective: initial_torso_fit
        # - milestone: 40
        #   batch:                  
        #     initial_torso_fit:
        #       iterations: 1
        #       optimizer: initial_torso_fit
        #       # scheduler: null
        #       steps:
        #         - preprocess
        #       objective: initial_torso_fit
    # predict:
    val:
      batch:
        openpose: 
      #   dataset1: &val
      #     metrics: [rmse, fid]
      #     steps: [autoencode, sample]
      #     termination: []
      #     tensors: [show_autoencoded]
      #   dataset2:
      #     metrics: [rmse]
      #     steps: [autoencode]
      #     termination: [bad_fit]
      #     tensors: [show_autoencoded]
      # epoch:
      #   metrics: []
      #   steps: [traversal]
      #   termination: []
      #   tensors: [show_traversals]
    # test:
  _monitoring_:
    fit:
      step:
        initial_torso_fit:
          frequency: 1
          # steps:
            # - show_mesh
          tensors:
            - save_params
            - show_mesh_step
      iter:
        initial_torso_fit:
          frequency: 1
          # steps:
            # - show_mesh
          tensors:
            - show_mesh_iter
          metrics:
            - fit_quality
          termination: [bad_fit]
      batch:
        log_results:
          frequency: 1
          # steps: []
          metrics:
            - fit_quality
          tensors:
            - show_mesh_batch
