# @package _global_

experiment:
  visdom_ip: localhost
  name: smplify_fits
  batch_size: 1
  workers: 1

engine:
  runner:
    deterministic: false # required for index add ops
    # gpus: '0'
    devices: 1
    num_sanity_val_steps: 0
  modules:
    rerun:
      memory_limit: 4GB
      world_coordinates: RFU
      annotations:
        plots:
          - key: gm_j2d
            color: green
          - key: vposer
          - key: bend
            color: magenta
          - key: shape
        parents:
          openpose: &openpose_parents
            - -1
            - 0
            - 1
            - 2
            - 3
            - 1
            - 5
            - 7
            - 1
            - 8
            - 9
            - 10
            - 8
            - 12
            - 13
            - 0
            - 0
            - 15
            - 16
            - 14
            - 19
            - 14
            - 11
            - 22
            - 11
          openpose_gt: *openpose_parents
        labels:
          openpose: &openpose_labels
            - nose
            - neck
            - rshoulder
            - relbow
            - rwrist
            - lshoulder
            - lelbow
            - lwrist
            - mhip
            - rhip
            - rknee
            - rankle
            - lhip
            - lknee
            - lankle
            - reye
            - leye
            - rear
            - lear
            - lbigtoe
            - lsmalltoe
            - lheel
            - rbigtoe
            - rsmalltoe
            - rheel
          openpose_gt: *openpose_labels