# @package _global_

_helpers_:
  optimizer_common: &lbfgsls
    type: lbfgsls
    params:
      max_iter: 30
      lr: 1.0

_moai_:  
  _collections_:
    _optimizers_:
      initial_torso_fit: 
        <<: *lbfgsls
        groups: global  # groups: expressive # global
      fine_fit_stage1:
        <<: *lbfgsls
        groups: [expressive] # groups: expressive # [global, expressive]
      # fine_fit_stage1:
      #   <<: *lbfgsls
      #   groups: [global, expressive] # groups: expressive # [global, expressive]
    _criteria_:
      bad_fit:
        rmse:
          rmse: [rmse]
          threshold: [10000.3] # pixels
      error:
        is_finite:
          monitor: [rmse]