# @package _global_

experiment:
  visdom_ip: localhost
  name: smplify_fits
  batch_size: 1
  workers: 1

engine:
  runner:
    deterministic: false # required for index add ops
    # gpus: '0'
    devices: 1
    num_sanity_val_steps: 0

# logging:
#   name: ${experiment.name}
  # loggers:
  #   visdom:
  #     name: ${experiment.name}
  #     ip: ${experiment.visdom_ip}

# visualization:
#   batch_interval: 1
  # visualizers:
  #   vector:
  #     name: ${experiment.name}
  #     ip: ${experiment.visdom_ip}
  #     vector: [body.betas]
  #     type: [box]

# export:
#   batch_interval: 1
#   exporters:
#     pkl:
#       path: .
#       keys: 
#         - translation
#         - embedding
#         - body.betas
#         - body.rotation
#         - body.left_hand
#         - body.right_hand
#         - body.jaw
#         - body.pose
#         - body.expression
#       mode: append