# @package _global_

_helpers_:
  optimizer_common: &lbfgsls
    _type_: lbfgsls
    _params_:
      max_iter: 30
      lr: 1.0
      tolerance_grad: 1e-9
      tolerance_change: 1e-12

_moai_:
  _definitions_:
    _collections_:
      _optimizers_:
        initial_torso_fit:
          <<: *lbfgsls
          _groups_: global # groups: expressive # global
        fine_fit_stage1:
          <<: *lbfgsls
          _groups_: [expressive] # groups: expressive # [global, expressive]
        # fine_fit_stage1:
        #   <<: *lbfgsls
        #   groups: [global, expressive] # groups: expressive # [global, expressive]
      _criteria_:
        bad_fit:
          rmse:
            rmse: [rmse]
            threshold: [1000.3] # pixels
        error:
          is_finite:
            monitor: [rmse]
