# @package _global_

experiment:
  visdom_ip: localhost
  name: smplify_fits
  batch_size: 1
  workers: 1

engine:
  runner:
    deterministic: false # required for index add ops
    # gpus: '0'
    devices: 1
    num_sanity_val_steps: 0
  modules:
    rerun:
      world_coordinates: RFU
      parents:
        openpose:
          - -1
          - 0
          - 1
          - 2
          - 3
          - 1
          - 5
          - 7
          - 1
          - 8
          - 9
          - 10
          - 8
          - 12
          - 13
          - 0
          - 0
          - 15
          - 16
          - 14
          - 19
          - 14
          - 11
          - 22
          - 11
      labels:
        openpose:
          - nose
          - neck
          - rshoulder
          - relbow
          - rwrist
          - lshoulder
          - lelbow
          - lwrist
          - mhip
          - rhip
          - rknee
          - rankle
          - lhip
          - lknee
          - lankle
          - reye
          - leye
          - rear
          - lear
          - lbigtoe
          - lsmalltoe
          - lheel
          - rbigtoe
          - rsmalltoe
          - rheel

# logging:
#   name: ${experiment.name}
  # loggers:
  #   visdom:
  #     name: ${experiment.name}
  #     ip: ${experiment.visdom_ip}

# visualization:
#   batch_interval: 1
  # visualizers:
  #   vector:
  #     name: ${experiment.name}
  #     ip: ${experiment.visdom_ip}
  #     vector: [body.betas]
  #     type: [box]

# export:
#   batch_interval: 1
#   exporters:
#     pkl:
#       path: .
#       keys: 
#         - translation
#         - embedding
#         - body.betas
#         - body.rotation
#         - body.left_hand
#         - body.right_hand
#         - body.jaw
#         - body.pose
#         - body.expression
#       mode: append