# @package model.monads.random

_target_: moai.monads.generation.tensor.torch.Random
shape: ???
mode: unit # one of [unit, normal]
scale: 1.0
includes_batch: false # whether shape includes the batch dim