# @package model.modules.skip

_target_: moai.modules.lightning.unet.SqueezeExcite
squeeze:  
  type: average2d
excite: 
  type: channel
  operation:
    type: linear
  activation:
    type: relu
  ratio: 0.25
mode: mul
expansion: 2 # is static should not be changed