# @package export.exporters._name_

_target_: moai.export.local.Image2d
types: [color] # or depth
colormaps: [none] # bone, etc.
transforms: [none] # minmax, etc.
mode: overwrite # [all, overwrite]
keys: ???
path: ???
extensions: ??? # [png, exr, jpg]