# @package model.components.decoder

_target_: moai.components.decoder.Convolutional
configuration:
  bottleneck_features: ???
  out_features: ???
  feature_block_divisor: 2
  blocks: []
convolution:
  type: conv2d
  params:
    kernel_size: 3
    stride: 1
    padding: 1
  activation:
    type: ${model.configuration.activation_type}
    params:
      inplace: true
prediction:
  convolution:
    type: conv2d
    params:
      kernel_size: 3
      stride: 1
      padding: 1
  activation:
    type: identity
    params:
      inplace: true
upscale:
  type: upsample2d
  params:
    kernel_size: 4
    stride: 2
