# @package model.components.decoder

_target_: moai.components.mlp.MLP

configuration:
  in_features: ???
  hidden_features: ???
  out_features: ???
  blocks: ???
  linear:
    type: ???
    activation:
      type: ???
      parameters:
        inplace: true
  prediction:
    type: ???
    activation:
      type: ???
      parameters:
        inplace: true