# @package model.parameters.optimization.optimizers._name_

_target_: moai.parameters.optimization.optimizers.AdaBound
lr: 0.001
betas: [0.9, 0.999]
final_lr: 0.1
gamma: 0.001
eps: 1e-8
weight_decay: 0.0
amsbound: false