# @package model.parameters.optimization.optimizers._name_

_target_: moai.parameters.optimization.optimizers.AdaBelief
lr: 0.001
betas: [0.9, 0.999]
eps: 1e-8
weight_decay: 0.0
amsgrad: false
weight_decouple: false
fixed_decay: false
rectify: false