# @package model.parameters.optimization.optimizers._name_

_target_: moai.parameters.optimization.optimizers.AdaFactor
lr: ???
eps2: [1.0e-30, 1.0e-3]
clip_threshold: 1.0
decay_rate: -0.8
beta1: ???
weight_decay: 0.0
scale_parameter: true
relative_step: true
warmup_init: false