# @package model.parameters.optimization.optimizers._name_

_target_: moai.parameters.optimization.optimizers.AdamP
lr: 1.0e-3
betas: [0.9, 0.999]
delta: 0.1
wd_ratio: 0.1
eps: 1.0e-8
weight_decay: 0.0
nesterov: false