# @package model.parameters.optimization.optimizers._name_

_target_: moai.parameters.optimization.optimizers.LARCAdam
lr: 0.001
betas: [0.9, 0.999]
eps: 1e-8
weight_decay: 0.0
amsgrad: false
trust_coefficient: 0.02
clip: true