# @package model.parameters.optimization.optimizers.lbfgs

_target_: torch.optim.LBFGS
lr: 1.0
max_iter: 20
max_eval: null
tolerance_grad: 1e-7
tolerance_change: 1e-9
history_size: 100
line_search_fn: null # null or strong_wolfe