# @package model.parameters.optimization.optimizers._name_

_target_: moai.parameters.optimization.optimizers.QHAdam
lr: 1.0e-3
betas: [0.9, 0.999]
nus: [1.0, 1.0]
weight_decay: 0.0
eps: 1.0e-8
decouple_weight_decay: false