# @package model.parameters.optimization.optimizers._name_

_target_: moai.parameters.optimization.optimizers.SGDP
lr: 1.0e-3
momentum: 0.0
dampening: 0.0
eps: 1.0e-8
weight_decay: 0.0
delta: 0.1
wd_ratio: 0.1
nesterov: false