# @package model.parameters.optimization.optimizers._name_

_target_: moai.parameters.optimization.optimizers.Yogi
lr: 1.0e-2
betas: [0.9, 0.999]
eps: 1.0e-3
weight_decay: 0.0
initial_accumulator: 1.0e-6