# @package model.monads.transform

_target_: moai.monads.geometry.Transformation
xyz_in_at: channel  # one of ['channel', 'row]
xyz_out_at: channel # one of ['channel', 'row]
transpose: false    # transpose matrix before use