# @package model

_target_: moai.networks.lightning.factory.VariationalAutoencoder
configuration:
  repeat_val: 7
  traversal_len: 7
  traversal_step: 0.25
  traversal_dim: -1
  traversal_init_value: -0.75
  linear:
    type: ???
    activation:
      type: ???
io:
  encoder:
    out: ???
  latent_dist_predictor:
    out: ???
  sampler:
    out: ???
  decoder:  
    out: ???
  generator:
    out: ???