# @package model.parameters.optimizers.adopt

_target_: moai.parameters.optimization.optimizers.adopt.ADOPT
lr: 0.0001
betas: [0.9, 0.999]
eps: 1e-6 # 1e-8
weight_decay: 0.0
decouple: false
foreach: null
maximize: false
capturable: false
differentiable: false
fused: null