# @package model.parameters.optimizers._name_

_target_: moai.parameters.optimization.optimizers.CentralizedSGD
lr: ???
momentum: 0.0
dampening: 0.0
weight_decay: 0.0
nesterov: false
gc_conv_only: false