# @package model.parameters.optimization.optimizers.lbfgsls

_target_: moai.parameters.optimization.optimizers.lbfgsls.LBFGS
lr: 1.0
max_iter: 20
max_eval: null
tolerance_grad: 1e-5
tolerance_change: 1e-9
history_size: 100
line_search_fn: strong_Wolfe