# @package model.parameters.optimizers._name_

_target_: moai.parameters.optimization.optimizers.SAdam
lr: 0.1
betas: [0.9, 0.999]
eps: 1.0e-8
weight_decay: 0.0
partial: 0.25
amsgrad: true
transformer: softplus
grad_transf: square
smooth: 50
hist: false
