# @package model.parameters.optimizers._name_

_target_: moai.parameters.optimization.optimizers.SWATS
lr: 0.001
betas: [0.9, 0.999]
weight_decay: 0.0
eps: 1e-8
amsgrad: false
verbose: false
nesterov: false
