# @package model.parameters.optimizers._name_

_target_: moai.parameters.optimization.optimizers.srone.SymmetricRankOneTrust
lr: 1.0
max_newton: 30
abs_newton_tol: 1e-5
rel_newton_tol: 1e-6
matrix_free_memory: 5 #null
trust_region:
  initial_radius: 0.1
  max_radius: 2.0 #1e4
  nabla0: 1e-4
  nabla1: 0.25
  nabla2: 0.5
  shrink_factor: 0.1
  growth_factor: 2.0
  trust_region_subproblem_solver: cg # null or cg
  trust_region_subproblem_tol: 1e-5
  trust_region_subproblem_iter: 10