# @package _global_

conv_type: conv2d
downscale_type: maxpool2d

model:
  configuration:
    stages: 4
    in_features: 1
    out_features: 18
    input: depth
    output: heatmaps_t_4
    global:
      convolution: conv2d
      activation: bn2d_relu
    preproc:
      stem:
        blocks: [conv2d, conv2d]
        convolutions: [conv2d, conv2d]
        activations: [bn2d_relu, bn2d_relu]
        kernel_sizes: [3, 3]
        features: [32, 64]
        strides: [2, 2]
        paddings: [1, 1]
      residual: 
        block: preactiv_bottleneck
        convolution: conv2d
        activation: bn2d_relu
        features:
          in_features: [64, 256]
          out_features: [256, 256]
          bottleneck_features: [64, 64]
    branches:
      start_features: 32
      modules: [3, 4, 4]
      depths: 
        - [3, 3, 3]
        - [3, 3, 2, 2]
        - [3, 3, 3, 4]
  modules:
    highres:
      residual:
        type: preactiv_bottleneck
        bottleneck_features: 128
      fuse:
        activation:    
          intermediate: bn2d_relu
          prefusion: bn2d
          final: relu
        upscale: 
          type: upsample2d
          conv_up: true
    start_transition:
      identity:
        kernel_size: 3
        stride: 1
        padding: 1
      branched:
        downscale: none
        kernel_size: 3
        stride: 2
        padding: 1
    stage_transition:
      branched:
        downscale: none
        kernel_size: 3
        stride: 2
        padding: 1
    head:
      activation: none
      kernel_size: 1
      padding: 0

  parameters:
    optimization:
      optimizers:
        adam:          
          lr: 2.0e-3

  monads:
    grid:
      width: 320  # x
      height: 160 # y     
      inclusive: false
      order: xy
      mode: ndc

    visibility_fov:
      width: 320  # x
      height: 160 # y  
      # order: xy
      coord_type: coord

    isotropic_gaussian:
      normalize: true
      scale: false
      grid_type: ndc

    # center_of_mass:
    #   flip: false

    interpolate:
      width: 80
      height: 40
      mode: nearest

    coordinate_decoding:
      mode: argmax
      flip: false

    gaussian2d:
      kernel_size: [5, 5]
      sigma: [1.0, 1.0]
      border_type: reflect

    dark:
      flip: false

    transform:
      xyz_in_at: row
      xyz_out_at: row
      transpose: false

    project:
      xyz_at: row
      uv_at: row
      uv_type: ndc


        
    # clamp:
    #   max_value: 1.0

    # threshold:
    #   value: 4.0  
      
  feedforward:
    preprocess:
      grid:
        tensor: [depth]
        out: [grid_ori]

      interpolate:
        image: [grid_ori]
        out: [grid]

      transform:
        points: [joints_3d]
        rotation: [campose_rotation]
        translation: [campose_translation]
        out: [joints_3d_view]

      project:
        intrinsics: [dintr]
        points: [joints_3d_view]
        grid: [grid]
        out: [joints_2d]

      isotropic_gaussian:
        keypoints: [joints_2d]
        grid: [grid]
        out: [heatmaps_gt]

      visibility_fov:
        coords: [joints_2d]
        out: [joints_2d_mask]

      # threshold:
      #   x: [M72j_depth]
      #   out: [depth_mask]

      # clamp:
      #   x: [M72j_depth]
      #   out: [depth]

    postprocess:
      spatial_softmax:
        tensor: [heatmaps_t_4]
        out: [heatmaps_t_4]
      
      coordinate_decoding:
        grid: [grid]
        heatmaps: [heatmaps_t_4]
        out: [raw_coords]
      
      gaussian2d:
        image: [heatmaps_t_4]
        out: [filtered_hm]
      
      dark:
        coords: [raw_coords]
        heatmaps: [filtered_hm]
        out: [kpts]

      # center_of_mass:
      #   grid: [grid]
      #   # heatmaps: [heatmaps_gt]
      #   heatmaps: [heatmaps_t_4]
      #   out: [kpts]
