# @package _global_

conv_type: conv2d
downscale_type: maxpool2d
model:
  configuration:
    stages: 4
    in_features: 1
    out_features: 18
    input: depth
    output: heatmaps_t_4
    global:
      convolution: conv2d
      activation: bn2d_relu
    preproc:
      stem:
        blocks: [conv2d, conv2d]
        convolutions: [conv2d, conv2d]
        activations: [bn2d_relu, bn2d_relu]
        kernel_sizes: [3, 3]
        features: [32, 64]
        strides: [2, 2]
        paddings: [1, 1]
      residual: 
        block: bottleneck
        convolution: conv2d
        activation: bn2d_relu
        features:
          in_features: [64, 256]
          out_features: [256, 256]
          bottleneck_features: [64, 64]
    branches:
      start_features: 32
      modules: [3, 4, 4]
      depths: 
        - [3, 3, 3]
        - [3, 3, 2, 2]
        - [3, 3, 3, 4]
  modules:
    highres:
      residual:
        type: bottleneck
        bottleneck_features: 128
      fuse:
        activation:    
          intermediate: bn2d_relu
          prefusion: bn2d
          final: relu
        upscale: 
          type: upsample2d
          conv_up: true
    start_transition:
      identity:
        kernel_size: 3
        stride: 1
        padding: 1
      branched:
        downscale: none
        kernel_size: 3
        stride: 2
        padding: 1
    stage_transition:
      branched:
        downscale: none
        kernel_size: 3
        stride: 2
        padding: 1
    head:
      activation: sigmoid
      kernel_size: 1
      padding: 0
      inplace: false

  parameters:
    optimization:
      optimizers:
        adam:          
          lr: 2.0e-3

  monads:
    grid:
      width: 320  # x
      height: 160 # y     
      inclusive: false
      order: xy
      mode: coord

    visibility_fov:
      width: 320  # x
      height: 160 # y  
      # order: xy
      coord_type: coord

    visibility_heatmap:
      threshold: 0.4

    isotropic_gaussian:
      std: 2
      normalize: false
      scale: false
      grid_type: coord

    transform:
      xyz_in_at: row
      xyz_out_at: row
      transpose: false

    project:
      xyz_at: row
      uv_at: row
      uv_type: coord

    interpolate:
      width: 80
      height: 40
      mode: nearest

    coordinate_decoding:
      mode: argmax
      flip: false

    gaussian2d:
      kernel_size: [5, 5]
      sigma: [1.0, 1.0]
      border_type: reflect

    dark:
      flip: false
      grid_type: coord
      
  feedforward:
    preprocess:
      grid:
        tensor: [depth]
        out: [grid_ori]      

      transform:
        points: [joints_3d]
        rotation: [campose_rotation]
        translation: [campose_translation]
        out: [joints_3d_view]

      interpolate:
        image: [grid_ori]
        out: [grid]

      project:
        intrinsics: [dintr]
        points: [joints_3d_view]
        grid: [grid_ori]
        out: [joints_2d]

      visibility_fov:
        coords: [joints_2d]
        out: [joints_2d_mask]

      isotropic_gaussian:
        keypoints: [joints_2d]
        grid: [grid_ori]
        masks: [joints_2d_mask]
        out: [heatmaps_gt_ori]

    postprocess:
      interpolate:
        image: [heatmaps_gt_ori]
        out: [heatmaps_gt]
      
      coordinate_decoding:
        grid: [grid]
        heatmaps: [heatmaps_t_4]
        out: [raw_coords]

      downscale_coords_x4:
        coords: [joints_2d, raw_coords]
        out: [joints_2d_low, raw_coords_low]
      
      gaussian2d:
        image: [heatmaps_t_4]
        out: [filtered_hm]
      
      dark:
        coords: [raw_coords_low]
        heatmaps: [filtered_hm]
        out: [kpts_low]

      visibility_heatmap:
        coords: [kpts_low]
        heatmaps: [filtered_hm]
        out: [kpts_mask]

      upscale_coords_x4:
        coords: [kpts_low]
        out: [kpts]

