# @package _global_

experiment:
  visdom_ip: localhost
  name: H4D_pose_regression
  batch_size: 16
  workers: 4


engine:
  modules:
    manual_seed:
      seed: 1337

trainer:
  gpus: "0"
  check_val_every_n_epoch: 1
  accumulate_grad_batches: 2
  max_epochs: 300
  weights_summary: top

logging:
  name: ${experiment.name}
  loggers:
    visdom:
      name: ${experiment.name}
      ip: ${experiment.visdom_ip}
    tabular:
      name: ${experiment.name}

visualization:
  batch_interval: 1
  visualizers:
    feature2d:                      
      name: ${experiment.name}
      ip: ${experiment.visdom_ip}
      keys: [M72j_heatmaps_gt, M72j_heatmaps]
      types: [color, color]
      colormaps: [turbo, turbo]
      transforms: [minmax, minmax]

    image2d:
      name: ${experiment.name}
      ip: ${experiment.visdom_ip}
      keys: [M72j_color]
      types: [color]
      colormaps: [none]
      transforms: [none]

    gizmo2d:
      name: ${experiment.name}
      ip: ${experiment.visdom_ip}
      images: [M72j_depth]
      gizmos: [marker_diamond]
      gt: [M72j_joints_2d]
      pred: [M72j_kpts]
      coords: [ndc]
      color_gt: [green]
      color_pred: [red]
      reverse_coords: [false]