# @package _global_

experiment:
  visdom_ip: localhost
  name: SSP3D_viz
  batch_size: 8
  workers: 1

visualization:
  batch_interval: 1
  visualizers:
    blend2d:
      name: ${experiment.name}
      ip: ${experiment.visdom_ip}
      left: [color, rendered_silhouette]
      right: [silhouette, silhouette]
      blending: [0.65, 0.5]
      colormap: [viridis_r, jet]
      transform: [none, none]
      scale: 1.0
    density2d:
      name: ${experiment.name}
      ip: ${experiment.visdom_ip}
      key: [shape_1-2, shape_2-3]
    pose2d:
      name: ${experiment.name}
      images: [color]
      poses: [human_pose2d]
      gt: [keypoints]
      pred: [joints2d]
      gt_masks: [confidence]
      pred_masks: [confidence]
      pose_structure:
        - [0, 1, 3]
        - [0, 2, 4]
        - [5, 7, 9]
        - [6, 8, 10]
        - [11, 13, 15]
        - [12, 14, 16]

        # - [1, 2, 3]
        # - [4, 5, 6]
        # - [0, 7, 8, 9, 10]        
        # - [11, 12, 13]
        # - [14, 15, 16]
      transparency: 0.5
      coords: [coord]
      color_gt: lime
      color_pred: pink
      reverse_coords: true
      scale: 1.0
      use_mask: false
    # rendered_mesh:
    #   name: ${experiment.name}
    #   ip: ${experiment.visdom_ip}
    #   batch_percentage: 1.0
    #   image: [color]
    #   colormap: [none]
    #   transform: [none]
    #   vertices: [vertices]
    #   faces: [faces]
    #   translation: [null] # [camera_translation]
    #   rotation: [null] # [camera_rotation_3x3]
    #   scale: 1.0

statistics:
  calculators:
    pairwise:
      key: [shape, shape]
      pair: [[1,2], [2,3]]