# @package model.validation

_target_: moai.validation.Collection
# @package model.validation.metrics._name_
metrics:
  top_accuracy:
    _target_: moai.validation.metrics.common.TopAccuracy
  top5_accuracy:
    _target_: moai.validation.metrics.common.Top5Accuracy
top_accuracy:
  gt: [label]
  pred: [prediction]
top5_accuracy:
  gt: [label]
  pred: [prediction]