# @package engine.modules.graylog_logging

_target_: moai.engine.modules.graylog_logging.GraylogLogging
host: ${env:HYDRA_GRAYLOG_HOST}
port: ${env:HYDRA_GRAYLOG_PORT}
level: ${env:HYDRA_GRAYLOG_LOG_LEVEL}