# @package model.modules.discriminator

_target_: moai.modules.lightning.MLP

configuration:
  in_features: ???
  hidden_features: ???
  out_features: ???
  blocks: ???
  linear:
    type: ???
    activation:
      type: ???
      parameters:
        inplace: true
  prediction:
    type: ???
    activation:
      type: ???
      parameters:
        inplace: true