# @package _global_

experiment:
  visdom_ip: localhost
  name: CelebA_disentanglement_VAE
  batch_size: 144
  workers: 4

trainer:
  gpus: '0'

logging:
  name: ${experiment.name}
  loggers:
    visdom:
      name: ${experiment.name}
      ip: ${experiment.visdom_ip}

visualization:
  batch_interval: 1
  visualizers:
    image2d:
      name: ${experiment.name}
      ip: ${experiment.visdom_ip}
      batch_percentage: 0.05
      keys: [color, generated]
      types: [color, color]
      colormaps: [none, none]
      transforms: [ndc, ndc]
  latent_visualizers:
    image_grid2d:
      name: ${experiment.name}
      ip: ${experiment.visdom_ip}
      keys: [color_grid]
      types: [color_grid]
      colormaps: [none]
      transforms: [ndc]