# @package model.monads.center_of_mass

_target_: moai.monads.distribution.CenterOfMass
mode: default # one of ['default', 'default_optimized_2d']
flip: true # whether to flip coords w.r.t grid coord order