# @package model.objectives.distance

_target_: moai.supervision.losses.regression.Distance
mode: default # one of ['vector', 'matrix', 'default', 'vector_auto', 'matrix_auto', 'default_auto']
order: 2.0
dim: -1