# @package model.parameters.optimization.optimizers._name_

_target_: moai.parameters.optimization.optimizers.srone.SymmetricRankOne
lr: 1.0
max_newton: 10
max_krylov: 10
abs_newton_tol: 1e-3
rel_newton_tol: 1e-6
krylov_tol: 1e-5
matrix_free_memory: 10 #null
line_search:
  max_searches: 5 #100
  extrapolation_factor: 0.1
  sufficient_decrease: 1.0e-4
  curvature_constant: null # float