# @package model.monads.mv_weak_perspective_camera

_target_: moai.monads.geometry.MVWeakPerspective
# focal_length: 5000.0
# principal_point: 0.5
# width: null
# height: null
# rotation: null
# translation: null
# persistent: false