# @package model.monads._name_

_target_: moai.monads.filter.highpass.Central3d
pad: reflect          # one of [reflect, replicate, zero]
reduction: magnitude  # one of [none, magnitude, abssum]
keep_size: false      # output same size (add padding)