# @package model.parameters.groups.expressive

_target_: moai.parameters.selectors.model.ModelParameterSelector
parameters:
  - preprocess.smplx.global_orient
monads:      
  - preprocess.translation
  - preprocess.betas
  - preprocess.embedding