# @package model.parameters.groups.global

_target_: moai.parameters.selectors.model.ModelParameterSelector
parameters:
  - preprocess.smplx.global_orient
  - preprocess.translation.value
force_grad: true