# @package _global_

experiment:
  visdom_ip: localhost
  name: HanCo_test_viz
  batch_size: 1
  workers: 8

visualization:
  batch_interval: 1
  visualizers:
    image2d:
      name: ${experiment.name}
      ip: ${experiment.visdom_ip}
      image: [color, mask_hand, mask_fg]
      type: [color, color, color]
      colormap: [none, gray, gray]
      transform: [none, none, none]