# @package _global_

experiment:
  visdom_ip: localhost
  name: HanCo_test_viz
  batch_size: 1
  workers: 1

visualization:
  batch_interval: 1
  visualizers:
    image2d:
      name: ${experiment.name}
      ip: ${experiment.visdom_ip}
      image: [color]
      type: [color]
      colormap: [none]
      transform: [none]