# @package _global_

all_depths: [M72i_depth, M72e_depth, M72h_depth, M72j_depth]
all_colors: [M72i_color, M72e_color, M72h_color, M72j_color]
all_rotation_d: [M72i_campose_rotation, M72e_campose_rotation, M72h_campose_rotation, M72j_campose_rotation]
all_translation_d: [M72i_campose_translation, M72e_campose_translation, M72h_campose_translation, M72j_campose_translation]
all_d_joints_3d: [M72i_joints_3d, M72e_joints_3d, M72h_joints_3d, M72j_joints_3d]
all_3d: [joints_3d, joints_3d, joints_3d, joints_3d]
all_grids: [grid, grid, grid, grid]
all_dintr: [M72i_dintr, M72e_dintr, M72h_dintr, M72j_dintr]
all_joints_2d: [M72i_joints_2d, M72e_joints_2d, M72h_joints_2d, M72j_joints_2d]
all_heatmaps_gt: [M72i_heatmaps_gt, M72e_heatmaps_gt, M72h_heatmaps_gt, M72j_heatmaps_gt]
all_heatmaps: [M72i_heatmaps, M72e_heatmaps, M72h_heatmaps, M72j_heatmaps]
all_kpts: [M72i_kpts, M72e_kpts, M72h_kpts, M72j_kpts]

conv_type: sconv2d
downscale_type: maxpool2d

model:
  configuration:
    in_features: 1
    input: ${all_depths}
    out_features: 18
    preproc:
      stem:
        kernel_size: 7
        stride: 1
        padding: 3

  modules:
    hourglass:
      features: 128
      depth: 1
      convolution: ${conv_type}
      downscale: ${downscale_type}

  parameters:
    optimization:
      optimizers:
        adam:          
          lr: 2.0e-3

  monads:
    grid:
      width: 160  # x
      height: 90 # y     
      inclusive: false
      order: xy
      mode: ndc

    isotropic_gaussian:
      normalize: true
      scale: false
      grid_type: ndc

    # center_of_mass:
    #   flip: false

    coordinate_decoding:
      mode: standard
      flip: false
   
    transform:
      xyz_in_at: row
      xyz_out_at: row
      transpose: false

    project:
      xyz_at: row
      uv_at: row
      uv_type: ndc
        
    clamp:
      max_value: 1.0

    threshold:
      value: 4.0  
      
  feedforward:
    preprocess:
      grid:
        tensor: ${all_depths}
        out: ${all_grids}

      transform:
        points: ${all_3d}
        rotation: ${all_rotation_d}
        translation: ${all_translation_d}
        out: ${all_d_joints_3d}

      project:
        intrinsics: ${all_dintr}
        points: ${all_d_joints_3d}
        grid: ${all_grids}
        out: ${all_joints_2d}

      isotropic_gaussian:
        keypoints: ${all_joints_2d}
        grid: ${all_grids}
        out: [M72j_heatmaps_gt]

    postprocess:
      spatial_softmax:
        tensor: ${all_heatmaps}
        out: ${all_heatmaps}
      
      coordinate_decoding:
        grid: ${all_grids}
        heatmaps: ${all_heatmaps}
        out: ${all_kpts}
