defaults:
  - engine: engine
  - engine/train: lightning
  - engine/visualization: visdom_cifar
  - engine/log/lightning/logger: visdom
  - data: cifar10
  - model/networks: lightning/classification/vgg11_bn
  - model/supervision: classification
  - model/parameters/optimization: sgd
  - model/validation: classification

NUM_CLASSES: 10
DATA_ROOT: ???

experiment:
  name: CIFAR10_classification