# @package model.components.head

_target_: moai.components.highres.AllBranchesHead
prediction:
  convolution: ${model.configuration.global.convolution}
  kernel_size: 3
  padding: 1
  activation: ${model.configuration.global.activation}
  inplace: True
projection:
  convolution: ${model.configuration.global.convolution}
  activation: none
  kernel_size: 1
  padding: 0
  inplace: True
upsample:
  mode: bilinear