# @package model.components.head

_target_: moai.components.lightning.highres.TopBranchHead
convolution: ${model.configuration.global.convolution}
activation: none
kernel_size: 1
padding: 0
inplace: True