# @package model.monads._name_

_target_: moai.monads.sampling.ScalePyramid
scales: null # float[] | 0 means invalid, either scale or dims need to be set
sizes: null  # int[] | -1 means invalid, either scale or dims need to be set
mode: bilinear # one of ['nearest', 'linear', 'bilinear', 'area', 'bicubic', 'trilinear']            
align_corners:  false
recompute_scale_factor: false
preserve_aspect_ratio: false