# @package _global_

experiment:
  name: CelebA_dataset_vizualization
  batch_size: 1
  workers: 1

visualization:
  batch_interval: 1
  visualizers:
    image2d:
      name: ${experiment.name}
      ip: "localhost"
      image: [color]
      type: [color]
      colormap: [none]
      transform: [dataset]