# @package model.monads.smplx

_target_: moai.monads.human.body.smpl.smplx.SMPLX
model_path: ???
joints_format: none
gender: neutral
age: adult
use_global_orientation: true
use_translation: true
use_pose: true
use_betas: true
use_hands: true
use_face: true
use_eyes: true
use_hands_pca: true
pca_components: 6
num_betas: 10
flat_hand_mean: false
use_face_contour: false
batch_size: 1