# @package _global_

model:
  monads:
    clamp:
      max_value: 8.0
    threshold:
      value: 8.0

  parameters:
    initialization:
      schemes:
        prediction_bias:
          bias: 3.0
          out_channels: 1
          kernel_size: 1
    optimization:
      optimizers:
        adam:
          lr: 1.0e-4
    schedule:
      schedulers:
        step:
          step_size: 20
          gamma: 0.5

  configuration:
    encoder:
      data: left_down_color
      out: [features, '']
    decoder:
      features: features
      out: left_down_depth_t
    activation_type: elu
    residual_type: preactiv_bottleneck

  modules:
    encoder:
      configuration:
        start_features: 64
      residual:
        bottleneck_factor: 0.5
        output_factor: 2.0
        block:
          setup: [3, 4, 6, 3]
    decoder:
      configuration:
        bottleneck_features: 2048
        out_features: 1
        blocks: [2, 2, 1, 1, 1, 1]
      prediction:
        convolution:
          params:
            kernel_size: 1
            padding: 0
        activation:
          type: relu

  feedforward:
    preprocess:
      threshold:
        x: [left_down_depth]
        out: [left_down_weights]
      clamp:
        x: [left_down_depth]
        out: [left_down_depth]