# @package _global_

experiment:
  name: multitask_depth_normal_3D60
  visdom_ip: localhost
  batch_size: 8
  workers: 2

trainer:
  gpus: "0"
  #fast_dev_run: true

visualization:
  batch_interval: 100
  visualizers:
    image2d:
      name: ${experiment.name}
      ip: ${experiment.visdom_ip}
      keys: [left_down_color, left_down_depth, left_down_depth_t, left_down_mask, left_down_normal, left_down_normal_t]
      types: [color, color, color, color, color, color]
      colormaps: [none, turbo, turbo, bone_r, none, none]
      transforms: [none, minmax, minmax, none, ndc, ndc]