# @package export.exporters._name_

_target_: moai.export.local.Image2d
type: [color] # or depth
colormap: [none] # bone, etc.
transform: [none] # minmax, etc.
mode: overwrite # [all, overwrite]
image: ???
path: ???
extension: ??? # [png, exr, jpg]