defaults:
  - engine: engine
  - engine/play: lightning
  - engine/visualization: collection
  - engine/visualization/visdom: image2d
  - engine/visualization/options: cifar
  - data/train/loader: torch
  - data/train/dataset/torchvision: cifar100
  - data/test/loader: torch
  - data/test/dataset/torchvision: cifar100
  - data/options: cifar100

CIFAR100_root_path: ???

experiment:
  name: CIFAR100_playback