# @package visualization.visualizers._name_

_target_: moai.visualization.clearml.Mesh
name: ${experiment.name}
vertices: ???
faces: ???
canvas: ???
layer: ???
color: ???
batch_percentage: 1.0
width: 600
height: 400
point_size: 0.1
max_history: 2