# @package visualization.visualizers._name_

_target_: moai.visualization.visdom.density2d.Density2d
name: ${experiment.name}
ip: "localhost" # pay attention this __NEEDS__ to be a "string"
key: ???
fill: true
palette: coral
levels: 10
width: 1920
height: 1080