# @package visualization.visualizers._name_

_target_: moai.visualization.visdom.Feature2d
name: ${experiment.name}
ip: "localhost" # pay attention this __NEEDS__ to be a "string"
image: ???
type: ???
colormap: ???
transform: ???