# @package visualization.visualizers._name_

_target_: moai.visualization.visdom.Image2d
name: ${experiment.name}
ip: "localhost" # pay attention this __NEEDS__ to be a "string"
batch_percentage: 1.0
keys: ???
types: ???
colormaps: ???
transforms: ???

