# @package visualization.visualizers._name_

_target_: moai.visualization.visdom.Image2d
name: ${experiment.name}
ip: "localhost" # pay attention this __NEEDS__ to be a "string"
port: 8097
batch_percentage: 1.0
image: [color]
type: [color]
colormap: [none]
transform: [none]