# @package visualization.visualizers._name_

_target_: moai.visualization.visdom.Vector
vector: ???
name: ${experiment.name}
ip: "localhost" # pay attention this __NEEDS__ to be a "string"
port: 8097
type: ???