_moai_:
  _collections_:
    _objectives_:
      train_encoder:
        cross_entropy:
          pred: [prediction]
          gt: [label]
          out: [train_loss]
    _optimizers_:
      train_encoder:
        _type_: adam
        _params_:
          lr: 1.0e-3
        _groups_: [encoder]
