# @package _global_

experiment:
  visdom_ip: localhost
  name: mnist_train
  batch_size: 256
  workers: 1

engine:
  modules:
    import:
      run_path: true
    manual_seed:
      seed: 1337
    clearml:
      project_name: Dev
      task_name: MNIST
      tags: [test]

fitter:
  deterministic: false # required for index add ops
  # gpus: '0'
  devices: 1
  num_sanity_val_steps: 0
  max_epochs: 2
  checkpoint:
    monitor: 'train/loss/train_loss'
    mode: 'min'
    filename: 'checkpoint_{epoch:02d}_{train_loss:.2f}'


logging:
  name: ${experiment.name}
  # loggers:
  #   visdom:
  #     name: ${experiment.name}
  #     ip: ${experiment.visdom_ip}